apiVersion: v1
kind: Service
metadata:
  name: nodeenv-app
  labels:
    app: app
spec:
  type: NodePort
  ports:
    - port: 8080
      name: app
      targetPort: 8888
  selector:
    app: app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  name: nodeenv-app-ingress
  namespace: default
spec:
  rules:
  - host: nodeenv.ingress.jmllab.com
    http:
      paths:
      - backend:
          serviceName: nodeenv-app
          servicePort: 8080
        path: /

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeenv-app
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        # Because kube-registry-proxy is present localhost access is via http instead of https
        image: __IMAGE__
        ports:
        - containerPort: 8888
