apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git
spec:
  type: git
  params:
    - name: revision
      value: stackato-3.6
    - name: url
      value: https://github.com/jmlambert78/node-env
